#!/bin/bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

if [ -f "$SCRIPTPATH"/theme.toml ]; then
	leftwm command "LoadTheme $SCRIPTPATH/theme.toml"
fi

xset r rate 300 40 &
picom &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
pgrep -x unclutter || unclutter -b -timeout 5 &
pgrep fcitx5 || fcitx5 &
"$HOME/.fehbg" &
xset s 1200 60;xss-lock -n dim-screen.sh -- screen_lock &
touchpad_toggle off &
pgrep -x greenclip || greenclip daemon &
pgrep -x dunst || dunst &
playerctld daemon &
# /usr/lib/kdeconnectd &
# pgrep -x tint2 || tint2 & sleep 2 && xdo move -x 0 -y 0 $(xdo id -n tint2) &
# $HOME/.config/polybar/launch.sh &
"$HOME/.config/eww/launch.sh" &
