border_width = 2
# margin = [25, 40]
margin = [20, 28]
# workspace_margin = [5, 8, 5, 8]
workspace_margin = [5, 15, 20, 15]
default_border_color = '#3c3836'
floating_border_color = '#83a598'
focused_border_color = '#f2e5bc'
# on_new_window = ''

# [[gutter]]
# side = "Bottom"
# value = 35

# [[gutter]]
# side = "Top"
# value = 35
