# my theme

hide_ascii         = false
prefer_small_ascii = true
spacing            = 2
padding            = 2
separator          = "->"
key_color          = "Cyan"
separator_color    = "Magenta"

[palette]
type            = "Full"
glyph           = "███"
visible         = false

[bar]
glyph           = "●"
symbol_open     = "("
symbol_close    = ")"
hide_delimiters = true
visible         = true

[box]
title           = "  Archlinux "
border          = "rounded"
visible         = true

[box.inner_margin]
x  = 0
y  = 0

[custom_ascii]
color           = "Blue"
path            = "~/.config/macchina/ascii/archlinux_small.ascii"

[randomize]
key_color       = false
separator_color = false

[keys]
host            = "Host"
kernel          = "Kernel"
battery         = "Battery"
os              = "OS"
de              = "DE"
wm              = "WM"
distro          = "Distro"
terminal        = "Terminal"
shell           = "Shell"
packages        = "Packages"
uptime          = "Uptime"
memory          = "Memory"
machine         = "Machine"
local_ip        = "IP"
backlight       = "Brightness"
resolution      = "Resolution"
cpu_load        = "CPU Load"
cpu             = "CPU"
