: ${FAST_HIGHLIGHT_STYLES[${FAST_THEME_NAME}default]::=none}
: ${FAST_HIGHLIGHT_STYLES[${FAST_THEME_NAME}unknown-token]::=fg=red,bold}
: ${FAST_HIGHLIGHT_STYLES[${FAST_THEME_NAME}commandseparator]::=none}
: ${FAST_HIGHLIGHT_STYLES[${FAST_THEME_NAME}redirection]::=none}
: ${FAST_HIGHLIGHT_STYLES[${FAST_THEME_NAME}comment]::=fg=8,bold}
: ${FAST_HIGHLIGHT_STYLES[${FAST_THEME_NAME}exec-descriptor]::=fg=yellow,bold}
: ${FAST_HIGHLIGHT_STYLES[${FAST_THEME_NAME}here-string-tri]::=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[${FAST_THEME_NAME}here-string-text]::=fg=18}
: ${FAST_HIGHLIGHT_STYLES[${FAST_THEME_NAME}here-string-var]::=fg=cyan,bg=18}
: ${FAST_HIGHLIGHT_STYLES[${FAST_THEME_NAME}secondary]::=clean}
: ${FAST_HIGHLIGHT_STYLES[${FAST_THEME_NAME}correct-subtle]::=fg=12}
: ${FAST_HIGHLIGHT_STYLES[${FAST_THEME_NAME}incorrect-subtle]::=fg=red}
: ${FAST_HIGHLIGHT_STYLES[${FAST_THEME_NAME}subtle-separator]::=fg=green}
: ${FAST_HIGHLIGHT_STYLES[${FAST_THEME_NAME}subtle-bg]::=bg=18}
