#!/usr/bin/bash
PIDFILE="$HOME/.cache/eww/$(basename $0).pid"
FIFOFILE="$HOME/.cache/eww/eww-fifo"

if [ "$DESKTOP_SESSION" != "qtile" ] || [ "$XDG_SESSION_DESKTOP" != "qtile" ];then
    exit 1
fi

if [ -f "$PIDFILE" ];then
    pid=$(cat "$PIDFILE")
    kill -TERM "$pid";sleep 1
    [ -f "$PIDFILE" ] && exit 1 || echo $$ > "$PIDFILE"
else
    echo $$ > "$PIDFILE"
fi

[ -e "$FIFOFILE" ] || mkfifo "$FIFOFILE"

cleanup() {
    exec 3>&-
    [ -e "$FIFOFILE" ] && rm -f "$FIFOFILE"
    rm -f "$PIDFILE"
    pkill -P $$
}

trap cleanup SIGINT SIGTERM EXIT

if [ "$DESKTOP_SESSION" == "qtile" ] || [ "$XDG_SESSION_DESKTOP" == "qtile" ];then
    while read -r line;do
        eww update "${line}"
    done <"$FIFOFILE" &
    exec 3>"$FIFOFILE"
    wait
fi

cleanup
