#!/usr/bin/bash
has() {
    _cmd=$(command -v "$1") 2>/dev/null || return 1
    [ -x "$_cmd" ] || return 1
}

if has lsb_release; then
    distro=$(lsb_release -sd)
elif [ -d /system/app ] && [ -d /system/priv-app ]; then
    distro="Android $(getprop ro.build.version.release)"

elif [ -f /etc/os-release ]; then
    while IFS='=' read -r key val; do
        case $key in
            (PRETTY_NAME)
                distro=$val
            ;;
        esac
    done < /etc/os-release

else
    has crux && distro=$(crux)
    has guix && distro='Guix System'
fi

distro=${distro##[\"\']}
distro=${distro%%[\"\']}

case $PATH in
    (*/bedrock/cross/*)
        distro='Bedrock Linux'
    ;;
esac
echo "$distro"
